### ISSUE TITLE
Last failed release pipeline on trunk branch(stag/qa whatever) block subsequent PR pipeline on same branch from getting merged

### ISSUE THREAD

**Issue by nagenderRawat** [jenkins-x/lighthouse#1118]
We have a use case where we have a `qa` branch(consider it as a main branch) and run CI steps for every PR made from diff feature branches(cut from qa and introduce additional changes) to `qa` and once those `feature => qa` PR are merged we use to run release pipeline for `qa` which does the CD stuff such that code is deployed on qa cluster.
Problem arise when a release pipeline got failed(for any reason) and causing lighthouse not to auto merge all subsequent PR's made on qa branch.

The details steps to reproducing are as follows -:
1. A developer cut/create a `feature/x` branch from qa.
2. Make change as per requirement of feature in the `feature/x` branch and raise **PR 101** to `qa` branch from `feature/x` (source branch).
3. As a result lighthouse triggers `pr` pullrequest pipeline(i.e a **presubmits** ) for **PR 101**, which basically does the CI(lint/test/sq etc) checks and if passes merges `feature/x` to `qa` branch.
4. Now the `qa` branch is having the new changes, so release pipeline runs, build the image and deploy if to **qa cluster**.

Now let suppose the release pipeline got failed(step 4) for some reason.

Now if  next developer wants to make a PR to from him own feature branch i.e `feature/y`, than this new PR from `feature/y => qa` will not be automatically merged because of the last release pipeline failed on `qa` branch and last release pipeline status getting pulled on the PR checks(can be seen in screenshot).

As a result subsequent PR's are not getting auto merged by lighthouse on `qa` branch once a release pipeline is failed on `qa` branch.

`.lighthouse/jenkins-x/triggers.yaml` looks like this
```
apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    trigger: "/test"
    rerun_command: "/retest"
    source: "pullrequest.yaml"
    branches:
    - qa
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - qa
```
lighthouse version -:
```
- chart: jenkins-x/lighthouse
  version: 0.0.851
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
```
**Using latest jenkins x 3 with tekton catalog.**

Please refer screenshot 
![Pull Request -1680](https://user-images.githubusercontent.com/22092981/96616062-bbc38900-131f-11eb-94fe-0694a5cfe363.png)
