### ISSUE TITLE
On /retest the pullrequest pipeline is picked from master branch instead of taking it from merge of PR branches

### ISSUE THREAD

**Issue by nagenderRawat** [jenkins-x/lighthouse#1119]
On `/retest` (after failing of PR pipeline) on PR comment a pipeline is triggered with `pullrequest.yaml` commited on master branch for the PR is raised on diff set of branches(for eg PR from `feature => qa`).

It should always use the pullrequest.yaml from the branches taking part in PR, no matter if it the first time or rerun after fail using `/retest`..

**Using jx3 alpha with tekton catalog**
jx cli -: `3.0.584`
Tekton version -:
```
- chart: cdf/tekton-pipeline
  version: 0.17.1
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
```
