### ISSUE TITLE
Support matrix style job definitions

### ISSUE THREAD

**Issue by garethjevans** [jenkins-x/lighthouse#1136]
GitHub Actions has a really clean syntax for supporting matrix job definitions e.g.

```
    strategy:
      matrix:
        os: [windows-2016, windows-2019, ubuntu-20.04]
        version: [8, 11, 14, 15]
        vm: [hotspot, openj9]
        package: [jdk, jre]
        runtype: [test]
```

It would be great if we could do something similar inside JX, ideally having each permutation appear as a separate check/build.  With the ability to retrigger/override each one.

**Comment by jstrachan** [comment]
this would be awesome. 

it might be nice to support a `matrix_presubmit` entry in the `.lighthouse/myfolder/triggers.yaml` file so that you could generate the matrix of presubmits which each have their own name / context, appear separately as separate checks on github and can have their own chatops trigger/rerun commands etc.

e.g.

```yaml
# .lighthouse/jenkins-x/triggers.yaml

# lets use a matrix to generate lots of presubmit contexts...
-  presubmit_matrix:
      matrix:
        os: [windows-2016, windows-2019, ubuntu-20.04]
        version: [8, 11, 14, 15]
        vm: [hotspot, openj9]
        package: [jdk, jre]
        runtype: [test]
```
which then effectively generates...
```
- presubmits:
  - name: windows-2016-8-hotspot-jdk-test 
    ...
  - name: windows-2019-8-hotspot-jdk-test
```

the main thing to figure out would be how to generate nice trigger/rerun expressions for each matrix combination. 

e.g. if you wanted to trigger `/test os:* version:8` for example. It might be nice to generate some canonical matrix trigger/rerun expressions.

Also it'd be nice to be able to specify which permutations are always run (or not). You may only want to always run a smaller subset of the matrix.

e.g. maybe something like...

```yaml
# .lighthouse/jenkins-x/triggers.yaml

-  presubmit_matrix:
      matrix:
        os: [windows-2016, windows-2019, ubuntu-20.04]
        version: [8, 11, 14, 15]
        vm: [hotspot, openj9]
        package: [jdk, jre]
        runtype: [test]
    always_run:
      os: [ubuntu-20.04]
      version: [15]
```
