### ISSUE TITLE
add more flexible triggering configuration

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/lighthouse#1222]
how that go-scm can handle deployments and a bunch of other webhooks (e.g. when a label is added to a PR, a deployment has been recorded, when a PR becomes unmergeable etc) it might be nice to add a GitHub Actions style configuration to trigger a pipeline using a number of filters. So in addition to the `presubmits` and `postsubmits` we could add something like...

```yaml
on:
# list the events and predicates
- # all the events that trigger the pipeline.... 
  release: {}
   label: 
     types: [created]
     name: ok-to-test 
   deployment: {}
   # now the usual presubmit/postsubmit job spec...
   name: cheese
   source: "cheese.yaml"
```

then folks can trigger a pipeline using any of the supported go-scm webhooks with per-webhook-kind filters
