### ISSUE TITLE
PipeLineValidation Error inrepo config 

### ISSUE THREAD

**Issue by stevejuma** [jenkins-x/lighthouse#1288]
Getting the following error message when trying to execute a pipeline defined using inrepo config.  Seems like tekton is complaining that additional parameters are being provided by the pipelinerun that don't exist in the task definition. Looking at the generated pipeline run I can see that there are indeed additional parameters being provided, I believe as a result of the changes in https://github.com/jenkins-x/lighthouse/pull/1135.  The exact error being thrown is by https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/taskrun/validate_resources.go#L93. I can get past the error now by adding the additional params in my git-clone task but seems weird that I have to do that. 

Lighthouse Version: `1.0.26` 

```bash
invalid input params for task git-clone: didn't need these params but they were provided anyway: [BUILD_ID JOB_NAME JOB_SPEC JOB_TYPE PULL_BASE_REF PULL_BASE_SHA PULL_NUMBER PULL_PULL_REF PULL_PULL_SHA PULL_REFS REPO_NAME REPO_OWNER REPO_URL]
```

`triggers.yaml`

```yaml
apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pull-test-prow-build 
    context: "ci-test"
    always_run: true
    optional: false
    trigger: "/test web"
    rerun_command: "/test web"
    source: "test.yaml"
  branchProtection:
    contexts:
    - ci-test
```

`test.yaml`
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-prow-test-
spec:
  serviceAccountName: app-builder
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    params:
      - name: REPO_NAME
        type: string
        description: The git repository URL to clone from.
      - name: REPO_URL
        type: string 
        description: The url for the repo
      - name: PULL_PULL_SHA
        type: string
        description: The branch to clone from the repo
    tasks:
      - name: git-clone
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: $(params.REPO_URL)
          - name: revision 
            value: $(params.PULL_PULL_SHA)
          - name: deleteExisting
            value: "true"
      - name: run-tests
        runAfter: 
        - git-clone
        workspaces:
        - name: source 
          workspace: shared-workspace
        taskSpec:
          workspaces:
            - name: source
          steps:
          - image: golang:alpine 
            name: run-tests
            script: |
              #!/bin/sh
              set -eu -o pipefail
              set -x
              cd $(workspaces.source.path)
              CGO_ENABLED=0 GOOS=linux go test
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: buildpacks-source-pvc
```
