### ISSUE TITLE
GitHub job status are updated despite Presubmit `skip_report` being set to `true`

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/lighthouse#1385]
My trigger file has `skip_report: true` enabled for my `create` Pipeline, however, the PR's still have `create` status appended.

```yaml
apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: pr
    context: "pr"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
  - name: create
    context: "create"
    always_run: false
    optional: true
    max_concurrency: 1
    skip_report: true
    source: "create.yaml"
  - name: cleanup
    context: "cleanup"
    always_run: false
    require_run: true
    optional: true
    max_concurrency: 1
    source: "cleanup.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
```
