### ISSUE TITLE
Possible to add commits after PR approval without owner review

### ISSUE THREAD

**Issue by dippynark** [jenkins-x/lighthouse#1387]
Maybe this is expected, but [this](https://github.com/jenkins-x/lighthouse/pull/1384) PR was LGMT'd and approved, but the tests weren't passing so I fixed them. The LGTM label was removed as expected, but the bot still merged the PR since the approved label remained, so I could have sneaked in malicious code.

Assuming Lighthouse is being used as the webhook handler, I think there are two solutions to this:

1) Change the tide/keeper plugin to exactly match the GitHub approve status (that is, if there are still checks that haven't completed like `Lighthouse Merge Status`, then do not attempt to merge). This way, GitHub's built-in merge protection can be enabled (e.g. requiring 1 approver, or requiring particular checks passing) without clashes. For example, in my personal testing, I see things like this because of this misalignment: https://github.com/dippynark/kfmt/pull/19#issuecomment-972649432 
2) Disable the approve plugin and only use the lgtm plugin to gate merging (since new commits cause the lgtm label to be removed) and change the Lighthouse tide/keeper config to be something like:

```
queries:
- labels:
   - lgtm
   missingLabels:
   - do-not-merge
   - do-not-merge/hold
   - do-not-merge/work-in-progress
   - needs-ok-to-test
   - needs-rebase
   repos:
   - jenkins-x/lighthouse
```
