### ISSUE TITLE
Bitbucket Server unable to trigger pipelines

### ISSUE THREAD

**Issue by Timoses** [jenkins-x/lighthouse#1393]
I believe due to the following one can never trigger jobs: https://github.com/jenkins-x/go-scm/issues/310

`IsCollaborator` will always fail.

```
[lighthouse-webhooks-c57dc69b9-q5w77] {"Branch":"master","Clone":"https://bitbucket.int/scm/test/testrepo.git","ID":"285","Link":"https://bitbucket.int/projects/test/repos/testrepo/browse","Name":"testrepo","Namespace":"TEST","Webhook":"pull_request","author":"myname","error":
"could not check membership: error in IsCollaborator: Not Authorized","level":"error","msg":"Error handling PullRequestEvent.","org":"TEST","pr":31,"repo":"testrepo","time":"2021-12-03T13:09:19Z","url":"https://bitbucket.int/projects/test/repos/testrepo/pull-requests/31"}
```
(Note: I set `GIT_CLONE_PATH_PREFIX=scm/` for the `webhooks` container. Otherwise it would have tried to clone from `https://bitbucket.int/test/testrepo`: https://github.com/jenkins-x/lighthouse/blob/f68e049c4cca44724d384c6480b1dd4ae3406adb/pkg/git/v2/remote.go#L128 )

plugins.yaml:
```
  plugins.yaml: |
    triggers:
      - repos:
        - TEST
        ignore_ok_to_test: false
        elide_skipped_contexts: false
        only_org_members: false
    owners:
      skip_collaborators:
        - TEST
    welcome:
      - repos:
        - TEST
        message_template: Nice to meet you @{{.AuthorLogin}} !
    plugins:
      TEST/testrepo:
        - trigger
        - lgtm
        - welcome
```

config.yaml:
```
apiVersion: v1
data:
  config.yaml: |
    pod_namespace: jx
    prowjob_namespace: jx
    in_repo_config:
      enabled:
        TEST: true
```

Unfortunately, it does not seem to be possible to configure `trigger` to only use the `OWNERS` file for info who may trigger jobs.

For `trigger` it always seems the first check:
https://github.com/jenkins-x/lighthouse/blob/main/pkg/plugins/trigger/pull-request.go#L45
(same for '/test <job>' comment in `generate-comment.go`)
