### ISSUE TITLE
Keeper unable to create SCM client for gitea

### ISSUE THREAD

**Issue by Timoses** [jenkins-x/lighthouse#1394]
```
    spec:
      containers:
      - args:
        - --namespace=jx
        env:
        - name: GIT_KIND
          value: gitea
        - name: GIT_SERVER
          value: http://gitea-dev-1-1.int:3000
        - name: GIT_USER
          value: testuser
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              key: oauth
              name: lighthouse-oauth-token
        - name: LOG_LEVEL
          value: trace
```

```
 k logs lighthouse-keeper-67886c596-g7gjz
{"component":"keeper","file":"/workspace/source/pkg/config/util/util.go:36","func":"github.com/jenkins-x/lighthouse/pkg/config/util.PathOrDefault","level":"warning","msg":"defaulting to /etc/config/config.yaml until 15 July 2019, please migrate","time":"2021-12-06T11:06:41Z"}
{"component":"keeper","fields.level":"debug","file":"/workspace/source/pkg/config/config.go:229","func":"github.com/jenkins-x/lighthouse/pkg/config.parseProwConfig","level":"info","msg":"setting the log level","time":"2021-12-06T11:06:41Z"}
{"component":"keeper","file":"/workspace/source/pkg/watcher/configmap_watcher.go:56","func":"github.com/jenkins-x/lighthouse/pkg/watcher.SetupConfigMapWatchers.func1","level":"info","msg":"updating the Lighthouse core configuration","time":"2021-12-06T11:06:41Z"}
{"component":"keeper","error":"cannot create SCM client: Get \"http://ansible-dev-1-1.mgmt.hss.int:3000/api/v1/version\": net/http: invalid header field value \"token 85f05921fb13ae970afef91697e533a9f4caf5bf\\n\" for key Authorization","file":"/workspace/source/cmd/keeper/main.go:142","func":"main.main","level":"fatal","msg":"Error creating Keeper controller.","time":"2021-12-06T11:06:41Z"}

```

I can successfully execute:

```
> curl -H 'Authorization: token 85f1fb13ae970afef91697e533a9fa5f' http://gitea-dev-1-1.int:3000/api/v1/version 
{"version":"1.15.7"}

```
(shortened token)
