### ISSUE TITLE
Triggers ignore namespace attribute

### ISSUE THREAD

**Issue by treyhyde** [jenkins-x/lighthouse#1405]
For a trigger defined as

```yaml
apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: e2e
    namespace: cypress-e2e
    context: "cypress/e2e"
    always_run: false
    require_run: true
    optional: false
    trigger: "/test"
    rerun_command: "/retest"
    source: e2e.yaml
    error_on_eviction: false
```

a LighthouseJob is created 

```yaml
kind: LighthouseJob
...
spec:
  agent: tekton-pipeline
  context: cypress/e2e
  job: e2e
  namespace: cypress-e2e
  pipeline_run_spec:
    pipelineSpec:
...
```

however, the PipelineRun is created in the `lighthouse` namespace, not `cypress-e2e` as I would expect.

```yaml
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
   ...
    name: ...cypress-e2e-8d9fk
    namespace: lighthouse
```
