### ISSUE TITLE
webhook Unable to detect OWNERS file, approve and lgtm plugin unable to work properly

### ISSUE THREAD

**Issue by zylpsrs** [jenkins-x/lighthouse#1430]
Deployment environment:

- webhook image is ghcr.io/jenkins-x/lighthouse-webhooks:1.5.11
- git server is gitea 1.15.8

plugins.yaml:

```yaml
approve:
- repos:
  - example/example-multi-repo
  lgtm_acts_as_approve: false
  require_self_approval: true
  
plugins:
  example:
  - size
  - pony
  - label
  - lgtm
  - approve
```
config.yaml:

```yaml
log_level: debug
in_repo_config:
  enabled:
    "*": true
pod_namespace: lighthouse
prowjob_namespace: lighthouse
tide:
  queries:
  - labels:
    - approved
    repos:
    - example/example-multi-repo
    - example/lighthouse-config
```

repo example-multi-repo include a OWNERS file:

```yaml
approvers:
- test
reviewers:
- test
```

when Open a pull request，robot return message:

```
[APPROVALNOTIFIER] This PR is NOT APPROVED

This pull-request has been approved by:
To complete the pull request process, please assign
You can assign the PR to them by writing /assign in a comment when ready.

The full list of commands accepted by this bot can be found here.

Needs approval from an approver in each of these files:
OWNERS
Approvers can indicate their approval by writing /approve in a comment
Approvers can cancel approval by writing /approve cancel in a comment
```
the OWNERS link is http://<gitea_server_url>/blob/master/OWNERS, Click to return 404 page not found, but my git server is gitea, the OWNERS can access via this address: http://<gitea_server_url>/raw/branch/master/OWNERS

webhook container log:

```
{"base":"master","client":"repoowners","error":"open /tmp/git669515402/OWNERS_ALIASES: no such file or directory","level":"info","msg":"No alias file exists at \"/tmp/git669515402/OWNERS_ALIASES\". Using empty alias map.","org":"example","repo":"lighthouse-config","time":"2022-03-08T02:31:53Z"}
{"client":"repoowners","level":"warning","msg":"AND OWNERS IS: \u0026{RepoAliases:map[] approvers:map[:map[\u003cnil\u003e:map[]]] reviewers:map[:map[\u003cnil\u003e:map[]]] requiredReviewers:map[] labels:map[] options:map[] baseDir:/tmp/git669515402 enableMDYAML:false dirExcludes:map[] log:0xc000111ab0}","time":"2022-03-08T02:31:53Z"}
```

However, when I create a OWNERS_ALIASES file, webhook can find it, but OWNERS file still can't used.
