### ISSUE TITLE
Lighthouse-keeper readinessprobe fails

### ISSUE THREAD

**Issue by jasperjonker** [jenkins-x/lighthouse#1462]
When I try to install Lighthouse in GKE, i get everything up and running, except the keeper pod. 
I get `Readiness probe failed: Get "http://10.120.2.240:8888/": dial tcp 10.120.2.240:8888: connect: connection refused`.

Logs: 
```json
{"component":"keeper","file":"/workspace/source/pkg/config/util/util.go:36","func":"github.com/jenkins-x/lighthouse/pkg/config/util.PathOrDefault","level":"warning","msg":"defaulting to /etc/config/config.yaml until 15 July 2019, please migrate","time":"2022-07-14T14:37:25Z"}
{"component":"keeper","controller":"sync","duration":"34.808µs","file":"/workspace/source/pkg/keeper/keeper.go:310","func":"github.com/jenkins-x/lighthouse/pkg/keeper.(*DefaultController).Sync.func1","level":"info","msg":"Synced","time":"2022-07-14T14:37:25Z"}
{"component":"keeper","error":"shutting down","file":"/workspace/source/pkg/keeper/status.go:94","func":"github.com/jenkins-x/lighthouse/pkg/keeper.(*statusController).shutdown","level":"info","msg":"shutting down the pool pending channel","time":"2022-07-14T14:37:25Z"}
{"component":"keeper","file":"/workspace/source/pkg/util/stopper.go:18","func":"github.com/jenkins-x/lighthouse/pkg/util.Stopper.func1","level":"warning","msg":"Interrupt received, attempting clean shutdown...","time":"2022-07-14T14:39:52Z"}
{"component":"keeper","file":"/workspace/source/pkg/interrupts/interrupts.go:63","func":"github.com/jenkins-x/lighthouse/pkg/interrupts.handleInterrupt","level":"info","msg":"Received signal.","signal":15,"time":"2022-07-14T14:39:52Z"}
{"component":"keeper","file":"/workspace/source/pkg/interrupts/interrupts.go:101","func":"github.com/jenkins-x/lighthouse/pkg/interrupts.WaitForGracefulShutdown.func1","level":"info","msg":"Interrupt received.","time":"2022-07-14T14:39:52Z"}
{"component":"keeper","file":"/workspace/source/pkg/interrupts/interrupts.go:179","func":"github.com/jenkins-x/lighthouse/pkg/interrupts.shutdown.func1","level":"info","msg":"Server shutting down...","time":"2022-07-14T14:39:52Z"}
{"component":"keeper","error":"http: Server closed","file":"/workspace/source/pkg/interrupts/interrupts.go:156","func":"github.com/jenkins-x/lighthouse/pkg/interrupts.ListenAndServe.func1","level":"info","msg":"Server exited.","time":"2022-07-14T14:39:52Z"}
{"component":"keeper","file":"/workspace/source/pkg/interrupts/interrupts.go:110","func":"github.com/jenkins-x/lighthouse/pkg/interrupts.WaitForGracefulShutdown","level":"info","msg":"All workers gracefully terminated, exiting.","time":"2022-07-14T14:39:52Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1526727]

goroutine 1 [running]:
github.com/jenkins-x/lighthouse/pkg/keeper.(*DefaultController).Sync(0xc0002d6210)
	/workspace/source/pkg/keeper/keeper.go:318 +0x207
main.sync({0x1bc8b98, 0xc0002d6210})
	/workspace/source/cmd/keeper/main.go:174 +0x2b
main.main()
	/workspace/source/cmd/keeper/main.go:150 +0x945
```

values.yaml:
```yaml
git:
  kind: github
  name: github
  server: https://github.com

user: "XXX"
oauthToken: "XXX"
hmacToken: "XXX"

cluster:
  crds:
    create: true

tektoncontroller:
  dashboardURL: "https://tekton.example.com"

engines:
  jx: false
  tekton: true


keeper:
  livenessProbe:
    initialDelaySeconds: 120

  readinessProbe:
    periodSeconds: 60
    successThreshold: 3
    timeoutSeconds: 5
```
Lighthouse version: 1.7.4

Does someone know how/why?
