### ISSUE TITLE
Orgs not supported on non-github repos

### ISSUE THREAD

**Issue by philhug** [jenkins-x/lighthouse#1505]
The following config does not work: (orgs are ignored)
````

    tide:
      queries:
      - labels:
        - approved
        - lgtm
        orgs:
        - myorg
        repos:
        - otherorg/myrepo
```

only `otherorg/myrepo` is processed and `myorg` is ignored.

See also code:
https://github.com/jenkins-x/lighthouse/blob/main/pkg/keeper/status.go#L481
