### ISSUE TITLE
Lighthouse-keeper "sync" failed to get the combined status

### ISSUE THREAD

**Issue by CPinhoK** [jenkins-x/lighthouse#1536]
## Environment
- Platform: (Kubernetes)
- Platform Version: (1.24.10)
- Tekton Version (0.35.1)
- Lighthouse Version (1.11.12)

During the installation process with tekton https://github.com/jenkins-x/lighthouse/blob/main/docs/install_lighthouse_with_tekton.md
at the step of approving the lighthouse-config repo pull request with the /approve the bot will reply with the correct message but it will not merge.

Upon viewing the lighthouse keeper pod there is this error
``` 
{"component":"keeper","file":"/workspace/source/pkg/config/util/util.go:36","func":"github.com/jenkins-x/lighthouse/pkg/config/util.PathOrDefault","level":"warning","msg":"defaulting to /etc/config/config.yaml until 15 July 2019, please migrate","time":"2023-04-27T16:28:18Z"}
{"component":"keeper","fields.level":"info","file":"/workspace/source/pkg/config/config.go:228","func":"github.com/jenkins-x/lighthouse/pkg/config.parseProwConfig","level":"info","msg":"setting the log level","time":"2023-04-27T16:28:18Z"}
{"component":"keeper","file":"/workspace/source/pkg/watcher/configmap_watcher.go:56","func":"github.com/jenkins-x/lighthouse/pkg/watcher.SetupConfigMapWatchers.func1","level":"info","msg":"updating the Lighthouse core configuration","time":"2023-04-27T16:28:18Z"}
{"component":"keeper","controller":"sync","file":"/workspace/source/pkg/keeper/keeper.go:1706","func":"github.com/jenkins-x/lighthouse/pkg/keeper.headContexts","level":"warning","msg":"'last' 0 commits didn't contain logical last commit. Querying GitHub...","time":"2023-04-27T16:28:19Z"}
{"component":"keeper","controller":"sync","error":"failed to get the combined status: Not Found","file":"/workspace/source/pkg/keeper/keeper.go:1858","func":"github.com/jenkins-x/lighthouse/pkg/keeper.restAPISearch","level":"error","msg":"Getting head contexts but ignoring.","time":"2023-04-27T16:28:20Z"}
{"component":"keeper","controller":"sync","duration":"1.856985693s","file":"/workspace/source/pkg/keeper/keeper.go:310","func":"github.com/jenkins-x/lighthouse/pkg/keeper.(*DefaultController).Sync.func1","level":"info","msg":"Synced","time":"2023-04-27T16:28:20Z"}
{"component":"keeper","error":"response: : http2: response body closed","file":"/workspace/source/cmd/keeper/main.go:175","func":"main.sync","level":"error","msg":"Error syncing.","time":"2023-04-27T16:28:20Z"}
```

My helm install values were : 
```
helm install lighthouse lighthouse/lighthouse -n ${install_namespace} -f <(cat <<EOF
git:
  kind: gitlab
  name: gitlab
  server: https://gitlab.com

user: "${bot_user}"
oauthToken: "${bot_token}"
hmacToken: "${webhook_secret}"

cluster:
  crds:
    create: true

tektoncontroller:
  dashboardURL: $tekton_dash_url

engines:
  jx: false
  tekton: true
EOF
)
```

for reference the config.yaml is 
```
pod_namespace: lighthouse
prowjob_namespace: lighthouse
tide:
  queries:
  - labels:
    - approved
    repos:
    - XXXX/YYYY/ZZZZ/lighthouse-config
```
and the plugins.yaml is 
```
approve:
- lgtm_acts_as_approve: false
  repos:
  - XXXX/YYYY/ZZZZ/lighthouse-config
  require_self_approval: true
config_updater:
  gzip: false
  maps:
    config.yaml:
      name: config
    plugins.yaml:
      name: plugins  
plugins:
  XXXX/YYYY/ZZZZ/lighthouse-config:
  - config-updater
  - approve
  - lgtm  
  - dog 
  - yuks
```
Does anyone know what is wrong in my deployment ?

I have also noticed the following error 
```
{"component":"keeper","controller":"status-update","error":"failed to get the combined status: Not Found","file":"/workspace/source/pkg/keeper/status.go:326","func":"github.com/jenkins-x/lighthouse/pkg/keeper.(*statusController).setStatuses.func1","level":"error","msg":"Getting head commit status contexts, skipping...","org":"XXXX","pr":4,"repo":"YYYY/lighthouse-config","sha":"dd035a0631ff45a4c8533844446781fa20e4f9fb","time":"2023-04-28T09:44:16Z"}
```
Sould the repo not be called YYYY/ZZZZ/lighthouse-config ?
