### ISSUE TITLE
Welcome plugin bug

### ISSUE THREAD

**Issue by CPinhoK** [jenkins-x/lighthouse#1541]
The welcome plugin is always activating on a new PR if all others created by the user have been closed/merged, if the user as another active pr in the repo the message will not trigger
```
welcome:
    - message_template: Welcome @{{.AuthorLogin}}! It looks like this is your first PR to org-xpto
    repos:
      - org-xpto
```
