### ISSUE TITLE
lighthouse chart uses jx-pipeline-git-(kind)-(name) secret in deployments but secret isn't available

### ISSUE THREAD

**Issue by abayer** [jenkins-x/lighthouse#465]
Since the `jx-auth-config` configmap started getting created, a boot+gitops cluster won't create secrets like `jx-pipeline-git-(kind)-(name)`...which is a problem for Lighthouse, which uses the following in its deployment configuration for its pods:

```
        - name: "GIT_USER"
          valueFrom:
            secretKeyRef:
              name: "jx-pipeline-git-{{ .Values.git.kind }}-{{ .Values.git.name }}"
              key: username
        - name: "GIT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "jx-pipeline-git-{{ .Values.git.kind }}-{{ .Values.git.name }}"
              key: password
          value: "{{ .Values.git.token }}"
```

@ccojocar - what should we be doing instead in this scenario?
