### ISSUE TITLE
Can Lighthouse Keeper wait for other merge checks

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/lighthouse#759]
Currently Lighthouse Keeper waits for Jenkins X pipelines that are defined in the Scheduler like `pr-build`.

Can we configure it to also wait for other merge checks?

We use github actions like: https://github.com/wagoid/commitlint-github-action and also [sonarcloud](https://sonarcloud.io/) to verify PRs

To sum up:

```sh
if approvals && pr-build = success && other-required-merge-checks = success && no-draft-labels
then
  merge
fi
```

**Comment by gazal-k** [comment]
tried adding to `entries` here: https://github.com/jenkins-x-charts/jxboot-resources/blob/master/jxboot-resources/templates/default-scheduler.yaml#L71-L74 like:

```yaml
      policy:
        Replace: false
        requiredStatusChecks:
          contexts:
            entries:
            - pr-build
            - commitlint
```

tried a bunch of different variations for `commitlint`, but `Lighthouse Merge Status` says:

'Not mergeable. Job commitlint has not succeeded.'

even when commitlint has succeeded
