### ISSUE TITLE
Support passing config.yaml and plugins.yaml to helm chart

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#906]
Would it be possible to support passing `config.yaml` and `plugins.yaml` directly when installing the helm chart ?

That would allow for using lighthouse without `config-updater`.

For example, this could be passed through `configMaps.config` and `configMaps.plugins`:

```yaml
configMaps:
  create: false
  config: null
  plugins: null
  configUpdater:
    orgAndRepo: ""
    path: ""
```

if `configMaps.config` or `configMaps.plugins` is not null, use this to initialize the config map.

The chart could be installed with:
```bash
helm install .... \
--set-file configMaps.config=./config.yaml \
--set-file configMaps.plugins=./plugins.yaml
```

I can open a PR if it's ok to add support for this.
