### ISSUE TITLE
Enable agent engine implementations to have their own job config fields

### ISSUE THREAD

**Issue by abayer** [jenkins-x/lighthouse#969]
Right now, we have to add any agent engine-specific field (like `PipelineRunSpec`) to `LighthouseJobSpec` and `JobBase`, which is not ideal at all. It should be possible for agent engine implementations to have their own arbitrary job configuration fields without requiring changes to `LighthouseJobSpec` and `JobBase`, so that we can actually support agent engines as "plugins".

**Comment by eddycharly** [comment]
How about an engine implementation has its own CRD ?

Then, a LighthouseJob could serve the purpose of creating the engine specific resource, this way the engine can use validation/mutating webhooks etc...

On top of that we could provide some primitives that help an engine implementor keep the engine specific resource in sync with the underlying lighthouse job (some things will have to stay in the lh job, git refs etc...).

**Comment by abayer** [comment]
My biggest question on that is how the presubmit/postsubmit job configuration works - it's fine if a `LighthouseJob` actually consists of multiple CRDs, but the `config` config map contents would still need to have the engine-specific fields...

**Comment by eddycharly** [comment]
Using `runtime.RawExtension` ?

**Comment by abayer** [comment]
Huh, interesting.

**Comment by eddycharly** [comment]
We could have something like:
`LighthouseJob` --(owner)--> `PipelineJob` --(owner)--> `PipelineRun`

And provide primitives/helpers so that the (now external) pipeline job controller can easily:
`LighthouseJob` <--(update status)-- `PipelineJob` <--(update status)-- `PipelineRun`

I mean a `LighthouseJob` mostly exists as a consequence of webhook and does nothing by itself, it's just there to help controllers in their jobs.

We could create `PipelineRun`s directly =)

**Comment by abayer** [comment]
Yeah, that all makes sense - I'm not really worried about the `LighthouseJob` side, but this bit:
```
presubmits:
  org/repo:
    - name: foo
      always_run: true
      rerun_command: /test this
      trigger: (?m)^/test( all| this),?(\s+|$)
      agent: tekton-pipeline
      pipelinerun_spec: ...
```

So how do we make it so that the presubmit/postsubmit configuration (whether it's living in the global `config` config map, or directly in a repo's own `lighthouse.yaml` or whatever) can be one piece but have engine-specific configuration? Do we do something like:
```
presubmits:
  org/repo:
    - name: foo
      (other common fields)
      engine_config:
        pipelinerun_spec: ...
```
where `engine_config` maps to something like ``EngineConfig map[string]interface{} `json:"engine_config,omitempty"` ``? And then we somehow attempt to deserialize the config? I'm not familiar/comfortable enough with go's deserialization magic...

**Comment by eddycharly** [comment]
Nope, we do something like this:

```yaml
presubmits:
  org/repo:
    - name: foo
      (other common fields)
      engine_resource:
        apiVersion: lighthouse.jenkins.io/v1alpha1
        kind: PipelineJob
        metadata:
          generateName: github-run-
        spec:
           // here comes the spec for the engine specific resource, probably a pipeline run for the pipeline engine, etc...
```

Hope it makes sense.
